### ISSUE TITLE
Assert vhost is not using the right connection url

### ISSUE THREAD

**Issue by rommik** [guidesmiths/rascal#133]
I'm running into this issue:

When `assert:true` is enabled, Rascal will perform assert using  `http://guest:guest@localhost:15672` instead of the url set in the connection. 

It will throw an exception that looks like `Failed to assert vhost: /. http://guest:***@localhost:15672 errored with: connect ECONNREFUSED 127.0.0.1:15672 `

Is this an issue with Rascal or RabbitMq?

Tech Info

```
  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
```

`rascal`:`~10.2.6`
`@types/rascal`:`~10.0.3`

`Broker Config`:
```
{
  "vhosts": {
    "/": {
      "assert": true,
      "check": true,
      "connection": {
        "url": "amqp://guest:guest@rabbitmq"
      },
      "exchanges": {
        "versions": {
          "type": "topic",
          "options": {
            "durable": true
          }
        }
      },
      "queues": {
        "master-5f41d7a1f5aa": {
          "options": {
            "durable": true,
            "messageTtl": 65000
          }
        }
      },
      "bindings": [
        "versions[versions.masters.*] ->master-5f41d7a1f5aa"
      ],
      "publications": {
        "who_is_online": {
          "vhost": "/",
          "exchange": "versions",
          "routingKey": "versions.agents.all"
        }
      },
      "subscriptions": {
        "i_am_online": {
          "vhost": "/",
          "queue": "master-5f41d7a1f5aa",
          "prefetch": 3
        }
      }
    }
  }
}
```
